doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            oat_question_id: 'OAT\Question\Infrastructure\Persistence\Doctrine\Type\DoctrineQuestionIdType'
            oat_question_text: 'OAT\Question\Infrastructure\Persistence\Doctrine\Type\DoctrineQuestionTextType'
            oat_question_created_at: 'OAT\Question\Infrastructure\Persistence\Doctrine\Type\DoctrineQuestionCreatedAtType'
            oat_question_choices: 'OAT\Question\Infrastructure\Persistence\Doctrine\Type\DoctrineQuestionChoicesType'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            OATUser:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/OAT/Question/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'OAT\Question\Domain'
